### ISSUE TITLE
`csvi </dev/null` crashes

### ISSUE THREAD

**Issue by d33tah** [ProfoundNetworks/csvinsight#10]
That's kind of rare, probably low-priority edge case, but you might want to track it:

```
INFO:csvinsight.cli:args: Namespace(config=None, delimiter=u'|', file=None, in_memory=False, list_fields=[], list_separator=u';', loglevel=20, stream=False, subprocesses=4, tempdir='/tmp')
Traceback (most recent call last):
 File "/home/d33tah/virtualenv/bin/csvi", line 11, in <module>
   sys.exit(main())
 File "/home/d33tah/virtualenv/local/lib/python2.7/site-packages/csvinsight/cli.py", line 154, in main
   header, histogram, results = _process_full(reader, args)
 File "/home/d33tah/virtualenv/local/lib/python2.7/site-packages/csvinsight/cli.py", line 90, in _process_full
   reader, list_columns=args.list_fields, list_separator=args.list_separator
 File "/home/d33tah/virtualenv/local/lib/python2.7/site-packages/csvinsight/split.py", line 104, in split
   header = next(reader)
StopIteration
```

**Comment by mpenkov** [comment]
We no longer read streams, so you can't pass /dev/null in anymore.

Nevertheless, reading from an empty file now raises ValueError:

```
(csvi)sergeyich:csvinsight misha$ csvi empty.csv
Traceback (most recent call last):
  File "/Users/misha/envs/csvi/bin/csvi", line 11, in <module>
    load_entry_point('csvinsight', 'console_scripts', 'csvi')()
  File "/Users/misha/pn/csvinsight/csvinsight/cli.py", line 204, in main
    header, histogram, results = _run_in_memory(reader, args)
  File "/Users/misha/pn/csvinsight/csvinsight/cli.py", line 93, in _run_in_memory
    reader, list_columns=args.list_fields, list_separator=args.list_separator
  File "/Users/misha/pn/csvinsight/csvinsight/split.py", line 195, in split_in_memory
    raise ValueError('Reader may not be empty')
ValueError: Reader may not be empty
```
